<!--
#################################################################
#                                                               #
# Copyright (c) 2022 YottaDB LLC and/or its subsidiaries.       #
# All rights reserved.                                          #
#                                                               #
#   This source code contains the intellectual property         #
#   of its copyright holder(s), and is made available           #
#   under a license.  If you do not know the terms of           #
#   the license, please stop and do not read further.           #
#                                                               #
#################################################################
-->
<template>
<div class="q-pa-md">
      <q-breadcrumbs gutter="xs" style="padding-left:10px;" id="breadcrumbs">
        <q-breadcrumbs-el label="Home" icon="home" :to="'/'"/>
        <q-breadcrumbs-el label="%XCMD Utility" icon="code" :to="'/xcmd'"/>
      </q-breadcrumbs>
  <q-card class="q-pa-md" flat bordered>
    <q-card-section horizontal>
      <q-card-section class="q-pt-xs">
        <div class="text-overline">System Management Utilities</div>
        <div class="text-h5 q-mt-sm q-mb-xs">%XCMD</div>
        <div class="text-caption text-grey">
          The ^%XCMD utility XECUTEs input from the shell command line and
          returns any error status (truncated to a single byte on UNIX)
          generated by that code.
        </div>
        <div class="text-caption text-blue">
          <a href="https://docs.yottadb.com/ProgrammersGuide/utility.html#xcmd"
            >More Info</a
          >
        </div>
      </q-card-section>
    </q-card-section>
    <q-card-section horizontal>
       <div class="q-pa-md">
        <div class="flex flex-center">
            <div class="row flex flex-center" >
      <div class="text-overline">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
      <codemirror
        :key="'code-panel' + 'single'+'-'+codeMirrorKey"
        class="codeMirrorXCMD"
        ref="cmEditorSingle"
        :value="singleCode"
        :options="cmOptions"
        @input="x => this.singleCode = x" 
      />
        </div>
        </div>
       </div>
    </q-card-section>
    <q-card-section>
      <div class="row flex flex-center bg-primary" >
<pre><code>{{getSingle}}</code></pre>
      </div>
    </q-card-section>
    <q-separator />

<div class="text-h6 q-mt-sm q-mb-xs">LOOP^%XCMD</div>
    <div class="q-pa-md">
    <div class="text-caption text-grey">
XECUTEs the arguments specified in –xec=/arg1/ as YottaDB code for each line of standard input that it reads.<br>
The currently read line is stored in the variable %l; its line number is stored in %NR (starts from 1).<br>
It returns any error status (truncated to a single byte on UNIX) generated by that code.<br>
–before=/arg0/ specifies the YottaDB code that LOOP^%XCMD must XECUTE before executing –xec.<br>
–after=/arg2/ specifies the YottaDB code that LOOP^%XCMD must XECUTE after executing the last –xec.<br><br><br>
</div>
    <q-card-section horizontal>
        <div class="flex flex-center">
            <div class="row flex flex-center" >
      <div class="text-overline">--before=</div>
      <codemirror
        :key="'code-panel' + 'before'+'-'+codeMirrorKey"
        class="codeMirrorXCMD"
        ref="cmEditorBefore"
        :value="beforeCode"
        :options="cmOptions"
        @input="x => this.beforeCode = x"
      />
        </div>
        </div>
    </q-card-section>
<br>
  <q-card-section horizontal>
        <div class="flex flex-center">
            <div class="row flex flex-center" >
      <div class="text-overline">--xec=&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
      <codemirror
        :key="'code-panel' + 'xec'+'-'+codeMirrorKey"
        class="codeMirrorXCMD"
        ref="cmEditorXec"
        :value="xecCode"
        :options="cmOptions"
         @input="x => this.xecCode = x"
      />
        </div>
        </div>
    </q-card-section>
    <br>
   <q-card-section horizontal>
        <div class="flex flex-center">
            <div class="row flex flex-center" >
      <div class="text-overline">--after=&nbsp;&nbsp;</div>
      <codemirror
        :key="'code-panel' + 'after'+'-'+codeMirrorKey"
        class="codeMirrorXCMD"
        ref="cmEditorAfter"
        :value="afterCode"
        :options="cmOptions"
        @input="x => this.afterCode = x"
      />
        </div>
        </div>
    </q-card-section>
    <q-card-section>
      <div class="row flex flex-center bg-primary" >
<pre><code>{{getLoop}}</code></pre>
      </div>
    </q-card-section>
    </div>
  </q-card>
</div>
</template>
<script>
import { codemirror } from "vue-codemirror";
import "codemirror/mode/mumps/mumps.js";
import { uid } from "quasar";
export default {
  components: {
    codemirror
  },
  watch:{
      '$q.dark.isActive': {
          handler(){
              this.$set(this.cmOptions,'theme',this.$q.dark.isActive ? "abcdef" : "default")
              this.codeMirrorKey = uid()
          }
      }
  },
  computed:{
    getSingle(){
      if (!this.singleCode){
        return ''
      } else {
        return '$ydb_dist/yottadb -run %XCMD \''+this.singleCode+'\''
      }
    },
    getLoop(){ 
      let output = '$ydb_dist/yottadb -run LOOP^%XCMD '
      if (!this.xecCode && !this.beforeCode && !this.afterCode){
        return ''
      } 
      if (this.beforeCode){
        output = output + '--before=\'/'+this.beforeCode+'/\' '
      }
      if (this.xecCode){
        output = output + '--xec=\'/'+this.xecCode+'/\' '
      }
      if (this.afterCode){
        output = output + '--after=\'/'+this.afterCode+'/\''
      }
    return output
    }
  },
  data() {
    return {
      codeMirrorKey:uid(),
      beforeCode: "",
      singleCode:'',
      xecCode:'',
      afterCode:'',
      cmOptions: {
        autofocus: true,
        tabSize: 4,
        mode: {
          name: "mumps"
        },
        theme: this.$q.dark.isActive ? "abcdef" : "default",
        lineNumbers: false,
        line: false
      }
    };
  }
};
</script>
<style>
@import "../../../node_modules/codemirror/lib/codemirror.css";
@import "../../../node_modules/codemirror/theme/abcdef.css";
.codeMirrorXCMD > .CodeMirror {
  border: 1px solid #eee;
  height: 30px;
  width:calc(100vw - 175px)!important;
}
</style>
